### PR TITLE
"urllib" to "requests" library change

### LINKED ISSUE #180: Migrate from urllib to requests
Instead of using `urllib`, the scrapper must be migrated to `requests` like other scrapers, unless there is a reason to stay with the former.

### PR DESCRIPTION
**Pull request by MUCCHU**
Fixes #180

Migrated the project from urllib to requests library. And also modified the import of `OrderedDict` and `defaultdict` from the collections framework. @benoit74 Kindly review my PR.

### CODE REVIEW

**Comment by MUCCHU** [comment]
While installing the requirements.txt file I faced issues when it was trying to install `zimscraperlib>=1.3.6,<1.4`. On installing without specifying any version, it worked flawlessly and installed version  `3.2.0`. Should I alter the version of zimscaperlib in the requirements file?

**Comment by benoit74** [comment]
Thank you for this contribution again, I'm unfortunately currently on holidays so I won't have time to review this in details until next week.

When you say that "it worked flawlessly", what did you tested specifically ? This scraper is known to have a major issue currently (https://github.com/openzim/openedx/issues/175) so I doubt you could really have tested something. And upgrading two major versions is not expected to go smoothly without any code change.

Regarding the issue you faced with `zimscraperlib>=1.3.6,<1.4`, which Python version did you used? This scraper is still on Python 3.8 and I can imagine such old zimscraperlib version might have issues with more recent Python versions (while obviously more recent zimscraperlib don't).

**Comment by jo780-full** [comment]
python 3.10.12 . I faced a similar issue

**Comment by benoit74** [comment]
Please use the proper Python version. If scraper is still on 3.8, there is 99% chance it won't work with 3.10

Or if you feel like you could do this, upgrade to more recent Python. We aim to support only one Python version per scraper, currently our target is 3.11 (zimscraperlib does not yet support 3.12).

**Comment by benoit74** [comment]
To be honest, I think you shouldn't spend too much time on this issue, the scraper is not working anymore and complex, you won't be able to really test your change. Taking an issue from youtube / ted / freecodecamp / kolibri / zimfarm would be more appropriate.

**Comment by benoit74** [comment]
Closing this for now, feel free to reopen if needed

**Pull request closed without merging**
